version: '3.8'
services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8080:80"
    volumes:
      - superset_home:/app/superset_home
    command: 
      - ./superset-init.sh

volumes:
  superset_home:
