version: '3.8'
services:
  superset:
    platform: linux/x86_64/v8
    build: .
    container_name: superset
    ports:
      - "8080:8080"
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
    volumes:
      - superset_home:/app/superset_home
    command: 
      - superset-init.sh

volumes:
  superset_home:
