version: '3.8'
services:
  superset:
    build: .
    container_name: superset
    ports:
      - "80:8088"
    volumes:
      - superset_home:/app/superset_home
    command: 
      - ./superset-init.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  superset-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: superset_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superset_db
    volumes:
      - superset_db_data:/var/lib/postgresql/data

volumes:
  superset_home:
  superset_db_data:
